# _config.yml
title: Personal Bio
email: example@example.com

# Configure navigation if your theme supports it
navigation:
  - name: Home
    link: /
  - name: Projects
    link: /#projects
  - name: Contact
    link: "mailto:example@example.com"
